---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: git-sync
  name: git-sync
spec:
  containers:
  - image: groob/git-sync
    name: git-sync
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
