apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-voll
spec:
  accessModes: 
      - ReadWriteOnce
  capacity: 
      storage: 1Gi
  hostPath:
      path: /tmp/data
      
      
# kubectl create -f pv-definition.yaml      

