---
apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
  - image: alpine
    name: alpine
    command:
    args:
    volumeMounts:
    - mountPath: /opt
      name: data-volume
    
    
  volumes:
  - name: data-volume
    hostpath:
      path: /data
      type: Directory
      
  - name: data-volume
    awsElasticBlockStore:
      volumeID: <volume-id>
      fsType: ext4
      
      
    
