---
apiVersion: v1
kind: pod
metadata:
  name: random-number-generator
spec:
  containers:
  - image: alpine
    name: alpine
    command:
    args:
    
    
  volumes:
  - name: data-volume
    hostpath:
      path: /data
      type: Directory
    
