---
apiVersion: v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  strategy: {}
  template:
    metadata:
      creationTimesatmp: null
      labels:
        app: webapp
    spec:
      containers:
      - image: nginx1.17.1
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
